// packages/ui-package/src/vue2/DemoStat.vue
<template>
  <div class="demo-stat">
    <div class="demo-stat__label">
      {{ label }}
      <slot name="label-extra" />
    </div>
    <div class="demo-stat__value">
      {{ display }}
      <span v-if="unit" class="demo-stat__unit">{{ unit }}</span>
    </div>
    <div class="demo-stat__delta" :class="deltaClass">环比 {{ deltaText }}</div>
  </div>
</template>

<script>
// 跨框架复用同一套格式化口径：这里吃的就是 @demo/shared-utils 的源码
import { formatPercent, formatCompact } from '@demo/shared-utils'

export default {
  name: 'DemoStat',
  props: {
    label: { type: String, required: true },
    value: { type: Number, required: true },
    unit: { type: String, default: '' },
    delta: { type: Number, default: 0 },
    compact: { type: Boolean, default: true }
  },
  computed: {
    display() {
      return this.compact ? formatCompact(this.value) : this.value.toLocaleString('zh-CN')
    },
    deltaText() {
      return formatPercent(this.delta)
    },
    deltaClass() {
      return this.delta > 0 ? 'is-up' : this.delta < 0 ? 'is-down' : ''
    }
  }
}
</script>

// packages/ui-package/src/react/DemoStat.tsx
import type { ReactNode } from 'react'
import { formatPercent, formatCompact } from '@demo/shared-utils'

export interface DemoStatProps {
  label: string
  value: number
  unit?: string
  /** 环比，正数为涨（红），负数为跌（绿） */
  delta?: number
  /** 大数字是否缩写为「万/亿」 */
  compact?: boolean
  labelExtra?: ReactNode
}

export function DemoStat({
  label,
  value,
  unit = '',
  delta = 0,
  compact = true,
  labelExtra
}: DemoStatProps) {
  const display = compact ? formatCompact(value) : value.toLocaleString('zh-CN')
  const deltaClass = delta > 0 ? 'is-up' : delta < 0 ? 'is-down' : ''

  return (
    <div className="demo-stat">
      <div className="demo-stat__label">
        {label}
        {labelExtra}
      </div>
      <div className="demo-stat__value">
        {display}
        {unit && <span className="demo-stat__unit">{unit}</span>}
      </div>
      <div className={`demo-stat__delta ${deltaClass}`}>环比 {formatPercent(delta)}</div>
    </div>
  )
}

export default DemoStat
