// packages/ui-package/src/vue3/DemoButton.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface DemoButtonProps {
  type?: 'default' | 'primary' | 'ghost' | 'danger'
  size?: 'small' | 'medium' | 'large'
  block?: boolean
  disabled?: boolean
}

const props = withDefaults(defineProps<DemoButtonProps>(), {
  type: 'default',
  size: 'medium',
  block: false,
  disabled: false
})

const emit = defineEmits<{ (e: 'click', ev: MouseEvent): void }>()

const classes = computed(() => [
  'demo-btn',
  props.type !== 'default' && `demo-btn--${props.type}`,
  props.size !== 'medium' && `demo-btn--${props.size}`,
  props.block && 'demo-btn--block',
  props.disabled && 'is-disabled'
])

function onClick(ev: MouseEvent) {
  if (props.disabled) return
  emit('click', ev)
}
</script>

<template>
  <button :class="classes" type="button" :disabled="disabled" @click="onClick">
    <slot />
  </button>
</template>

// packages/ui-package/src/react/DemoButton.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'

export interface DemoButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
  type?: 'default' | 'primary' | 'ghost' | 'danger'
  size?: 'small' | 'medium' | 'large'
  block?: boolean
  disabled?: boolean
  children?: ReactNode
}

export function DemoButton({
  type = 'default',
  size = 'medium',
  block = false,
  disabled = false,
  children,
  className,
  onClick,
  ...rest
}: DemoButtonProps) {
  const classes = [
    'demo-btn',
    type !== 'default' && `demo-btn--${type}`,
    size !== 'medium' && `demo-btn--${size}`,
    block && 'demo-btn--block',
    disabled && 'is-disabled',
    className
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <button
      {...rest}
      type="button"
      className={classes}
      disabled={disabled}
      onClick={(ev) => {
        if (disabled) return
        onClick?.(ev)
      }}
    >
      {children}
    </button>
  )
}

export default DemoButton
